feat: add booking function
IvanKondrashkov/java-shareit pull request #2
Opened 2022-12-19 14:16 UTC by IvanKondrashkov

2022-12-19 17:56 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе, часть из них по код стайлу. Жду новую версию

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingInfoDto> findAllByBooker(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestParam(name = "state", defaultValue = "ALL") String state) {
Слишком длинные строки с аргументами, сделайте переносы аргументов

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/StartBeforeEndValidator.java
> +        LocalDateTime start = bookingDto.getStart();
Нам не нужно проверять, что даты != null?

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repo/BookingRepository.java
> +    @Query("select b from Booking b where b.booker.id = ?1")
Лучше стараться обходиться без аннотации query там где это возможно и укладывать запрос в названии метода. Это делается для того, чтобы если вы смените драйвер и БД, Вам не пришлось переписывать все запросы под определенную БД

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repo/BookingRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        final Booking b = bookingRepository.save(booking);
переменные в java не принято так называть. Назовите booking или как то так

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return null;
Лучше не null возвращать, а исключение в default блоке свитча, ведь это нештатная ситуация будет

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public CommentInfoDto saveComment(@Validated({Create.class}) @RequestBody CommentDto commentDto, @RequestHeader("X-Sharer-User-Id") Long userId, @PathVariable Long id) {
Слишком длинная строка

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repo/ItemRepository.java
> +    @Query("select i from Item i where i.available = true and (lower(i.name) like lower(concat('%', ?1, '%')) or lower(i.description) like lower(concat('%', ?1, '%')))")
Переносы в строчке

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return null;
Нужно бросать исключение в switch, это ведь нештатная ситуация

2022-12-19 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
>      /**
Вообще над такими простыми методами не вижу смысла оставлять javadoc он на мой взгляд тут бесполезен, но в целом оставляю на ваше усмотрение

2022-12-19 17:56 UTC, Frilock commented on src/main/resources/schema.sql
> +    description VARCHAR(300) NOT NULL,
Размеры полей которые вы тут указываете лучше так же указывать в аннотации column, чтобы не приходилось каждый раз лезть в скритпы, чтобы узнать размерность поля в БД

2022-12-20 14:53 UTC, IvanKondrashkov commented on src/main/java/ru/practicum/shareit/booking/repo/BookingRepository.java
> +    @Query("select b from Booking b where b.booker.id = ?1")
Не понял причем здесь диалект, если используется объектная модель при построении запроса, т.е. мы обращаемся к полям сущности.

2022-12-20 14:57 UTC, IvanKondrashkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        final Booking b = bookingRepository.save(booking);
На вебинаре Владимир, называл так переменные которые приходят из БД, booking - сущность которую мы мапим из dto, b - это обёртка получаемая из репозитория.

2022-12-21 17:56 UTC, Frilock approved these changes
Принято, в комментарии указал, как можно конструкцию с Optional упростить

2022-12-21 17:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional.ofNullable(item.getName()).ifPresent(opt -> itemWrap.setName(item.getName()));
Достаточно так -  Optional.ofNullable(item.getName()).ifPresent(itemWrap::setName);

2022-12-22 12:51 UTC, closed without merging